name: Test changes
on:
  pull_request:
    branches:
      - main
      - staging
  push:
    branches:
      - main
      - staging
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm test
        env:
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
          GRINDERY_NEXUS_REFRESH_TOKEN: ${{ secrets.GRINDERY_NEXUS_REFRESH_TOKEN }}
          USER_ID_TEST: ${{ secrets.USER_ID_TEST }}
          RETRIES: ${{ secrets.RETRIES }}
